### ISSUE TITLE
Bug+Fix. Stacktrace:  'ConnectionRefusedError: [Errno 111] Connection refused' when running example from README,

### ISSUE THREAD

**Issue by zrthstr** [project-mk-ultra/torrent-tracker-scraper#61]
When running the example from the README if get a stack trace. This is due to and uncaught exception.
#62 

```
from torrent_tracker_scraper import scraper

scraper = scraper.Scraper(
    infohashes=[
        "82026E5C56F0AEACEDCE2D7BC2074A644BC50990",
        "04D9A2D3FAEA111356519A0E0775E5EAEE9C944A",
    ]
)
results = scraper.scrape()
print(results)
```

Produces:

```
zrth@fbb ~/test/libgen_torrent_cardiography % python tts.py
['82026E5C56F0AEACEDCE2D7BC2074A644BC50990', '04D9A2D3FAEA111356519A0E0775E5EAEE9C944A']
INFO:torrent_tracker_scraper.scraper:Scraping infohashes: ['82026E5C56F0AEACEDCE2D7BC2074A644BC50990', '04D9A2D3FAEA111356519A0E0775E5EAEE9C944A']
DEBUG:torrent_tracker_scraper.scraper:Parsing list of infohashes [exodus.desync.com:6969]
[...]
ERROR:torrent_tracker_scraper.scraper:Socket timeout for tracker.torrent.eu.org:451: timed out
DEBUG:torrent_tracker_scraper.scraper:Parsing list of infohashes [tracker.nrx.me:6969]
ERROR:torrent_tracker_scraper.scraper:Socket timeout for pow7.com:80: timed out
multiprocessing.pool.RemoteTraceback:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/zrth/.local/lib/python3.9/site-packages/torrent_tracker_scraper/scraper.py", line 223, in scrape_tracker
    response_transaction_id, connection_id = self._connect_request(
  File "/home/zrth/.local/lib/python3.9/site-packages/torrent_tracker_scraper/scraper.py", line 140, in _connect_request
    res = self.connection.sock.recv(16)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/zrth/test/libgen_torrent_cardiography/tts.py", line 12, in <module>
    results = scraper.scrape()
  File "/home/zrth/.local/lib/python3.9/site-packages/torrent_tracker_scraper/scraper.py", line 270, in scrape
    results = list(filter(lambda result: result != [], results.get()))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
ConnectionRefusedError: [Errno 111] Connection refused
```

We fix this by adding the following in scraper line 234:

```

except ConnectionRefusedError as e:
            logger.error("Connection refused for %s: %s", self.connection, e)
            return ["Connection refused for %s: %s" % (self.connection, e)]
```

**Comment by zrthstr** [comment]
#62

**Comment by 49e94b8f256530dc0d41f740dfe8a4c1** [comment]
Fixed and verified
